version: '3'
services:
  web:
    build: .
    container_name: factory_django
    restart: always
    ports:
      - '8000:8000'
    networks:
      my-net:
        ipv4_address: 172.21.0.3
networks:
  my-net:
    external: true
