# Generated by Django 3.2.12 on 2022-04-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220404_1628'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('flag_leave', models.BooleanField(default=False, verbose_name='请假')),
                ('flag_business', models.BooleanField(default=False, verbose_name='出差')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='上班时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='下班时间')),
                ('supplement', models.CharField(blank=True, default='无', max_length=100, null=True, verbose_name='补充')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='姓名')),
            ],
            options={
                'ordering': ['-current_time'],
                'unique_together': {('current_time', 'staff_name')},
            },
        ),
    ]
