# Generated by Django 3.2.12 on 2022-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='current_time',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(verbose_name='下班时间'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(verbose_name='上班时间'),
        ),
    ]
