# Generated by Django 3.2.12 on 2022-04-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '原料信息',
                'verbose_name_plural': '原料信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_version', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='WarehouseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('number', models.IntegerField(null=True, verbose_name='数量')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='单位')),
                ('source_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.goods', verbose_name='原料类型')),
            ],
            options={
                'verbose_name': '原料仓库信息',
                'verbose_name_plural': '原料仓库信息',
                'ordering': ['-current_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('number', models.IntegerField(null=True, verbose_name='数量')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='单位')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '产品仓库信息',
                'verbose_name_plural': '产品仓库信息',
                'ordering': ['-current_time'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_version', models.CharField(max_length=100, verbose_name='型号')),
                ('good_num', models.IntegerField(verbose_name='数量')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('sanction_date', models.DateField(auto_now=True, null=True, verbose_name='批准日期')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='单价')),
                ('total_price', models.BigIntegerField(blank=True, null=True, verbose_name='总价')),
                ('buyer_date', models.DateField(auto_now=True, null=True, verbose_name='采购日期')),
                ('status', models.SmallIntegerField(choices=[(1, '编辑'), (2, '审核'), (3, '采购')], default=1, verbose_name='状态')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='单位')),
                ('apply_staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_a', to='user.userprofile', verbose_name='申请人')),
                ('buyer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_c', to='user.userprofile', verbose_name='采购员')),
                ('good_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.goods', verbose_name='原料类型')),
                ('sanction_staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_b', to='user.userprofile', verbose_name='批准人')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
                'ordering': ['-apply_date'],
            },
        ),
        migrations.CreateModel(
            name='ProduceDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('today_done_num', models.IntegerField(default=0, verbose_name='今日产量')),
                ('qualified_num', models.IntegerField(default=0, verbose_name='合格量')),
                ('status', models.SmallIntegerField(choices=[(1, '编辑'), (2, '确认')], default=1, verbose_name='状态')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='单位')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='产品')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userprofile', verbose_name='员工')),
            ],
            options={
                'verbose_name': '生产信息',
                'verbose_name_plural': '生产信息',
                'ordering': ['-current_time'],
            },
        ),
    ]
