# Generated by Django 3.2.12 on 2022-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producediary',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '编辑'), (2, '确认')], default=1, verbose_name='状态'),
        ),
    ]
