# Generated by Django 3.2.12 on 2022-04-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_producediary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='good_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.goods', verbose_name='原料类型'),
        ),
    ]
