# Generated by Django 3.2.12 on 2022-04-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_purchaselist_good_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
