# Generated by Django 3.2.12 on 2022-03-30 02:28

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('staff_code', models.CharField(max_length=32, verbose_name='员工编号')),
                ('staff_phone', models.CharField(max_length=11, verbose_name='员工手机号')),
                ('staff_age', models.PositiveIntegerField(verbose_name='年龄')),
                ('staff_home', models.CharField(max_length=100, verbose_name='籍贯')),
                ('staff_gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('staff_nationality', models.CharField(max_length=20, verbose_name='民族')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('salary_pre_hour', models.IntegerField(verbose_name='时薪')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.position')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
