# Generated by Django 3.2.12 on 2022-04-02 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='操作标题')),
                ('code', models.CharField(max_length=32, verbose_name='方法')),
            ],
            options={
                'verbose_name': '操作信息',
                'verbose_name_plural': '操作信息',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '菜单信息',
                'verbose_name_plural': '菜单信息',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限标题')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的URL')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.action', verbose_name='操作')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.menu', verbose_name='菜单')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.permission', verbose_name='父权限')),
            ],
            options={
                'verbose_name': '权限信息',
                'verbose_name_plural': '权限信息',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='角色描述')),
                ('permissions', models.ManyToManyField(blank=True, to='user.Permission', verbose_name='拥有的所有权限')),
            ],
            options={
                'verbose_name': '角色信息',
                'verbose_name_plural': '角色信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('staff_code', models.CharField(max_length=32, unique=True, verbose_name='员工编号')),
                ('staff_phone', models.CharField(max_length=11, verbose_name='员工手机号')),
                ('staff_age', models.PositiveIntegerField(verbose_name='年龄')),
                ('staff_home', models.CharField(max_length=100, verbose_name='籍贯')),
                ('staff_gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('staff_nationality', models.CharField(max_length=20, verbose_name='民族')),
                ('id_card', models.CharField(max_length=20, unique=True, verbose_name='身份证')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('salary_pre_hour', models.IntegerField(verbose_name='时薪')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('roles', models.ManyToManyField(blank=True, related_name='roles', to='user.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
