# Generated by Django 3.2.12 on 2022-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_age',
            field=models.PositiveIntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff_home',
            field=models.CharField(max_length=100, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff_nationality',
            field=models.CharField(max_length=20, null=True, verbose_name='民族'),
        ),
    ]
