# Generated by Django 3.2.12 on 2022-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220401_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_card',
            field=models.CharField(max_length=20, unique=True, verbose_name='身份证'),
        ),
    ]
