# Generated by Django 3.2.12 on 2022-04-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='员工编号'),
        ),
    ]
