# Generated by Django 3.2.12 on 2022-04-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_client', models.CharField(max_length=100, verbose_name='客户名称')),
                ('order_number', models.IntegerField(verbose_name='数量')),
                ('order_price', models.IntegerField(verbose_name='单价(元)')),
                ('order_total_price', models.IntegerField(verbose_name='总价(元)')),
                ('order_time', models.DateField(auto_now_add=True, verbose_name='订货时间')),
                ('order_end', models.DateField(verbose_name='交货时间')),
                ('order_supplement', models.TextField(blank=True, null=True, verbose_name='补充')),
                ('status', models.SmallIntegerField(choices=[(1, '下单'), (2, '完成')], default=1, verbose_name='订单状态')),
                ('order_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='产品名称')),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
    ]
