# Generated by Django 3.2.12 on 2022-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_end',
            field=models.DateField(null=True, verbose_name='交货时间'),
        ),
    ]
